#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Module-CPANTS
version:      0.20030913
version_from: lib/Module/CPANTS.pm
installdirs:  site
requires:
    Test::More:                    0.01

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_03
