--- #YAML:1.0
name: Module-CPANTS
version: 0.003
license: perl
distribution_type: module
requires:
  CPANPLUS: 0.042
  Test::More: 0.01
recommends: {}
build_requires: {}
conflicts: {}
generated_by: Module::Build version 0.16
